### ISSUE TITLE
It might be something wrong with the gif  frame speed

### ISSUE THREAD

**Issue by baicker** [redphx/apixoo#1]
first of all, it's a awesome work, thanks very much

the original gif 
![727Streets of Rage 4](https://github.com/redphx/apixoo/assets/7483947/a3c6bade-e712-457f-8774-fee500316044)

the decoded gif from https://f.divoom-gz.com/group1/M00/06/C7/eEwpPWGdVBqES4UFAAAAAPBFftw4527421
![output](https://github.com/redphx/apixoo/assets/7483947/d6e8cbc8-62de-4080-8c23-ae6f7ca428f3)

**Comment by redphx** [comment]
Yeah I know the speed is not working properly. Thanks for the example, I'll check it later.

**Comment by baicker** [comment]
maybe this is the key, but i don't know how to fix 
![image](https://github.com/redphx/apixoo/assets/7483947/66b724d7-6a55-4e61-8885-b943696469fc)
![image](https://github.com/redphx/apixoo/assets/7483947/0d91deba-7825-4cd5-9385-261d28e49840)
![image](https://github.com/redphx/apixoo/assets/7483947/85be8de5-be53-4e1f-bb92-afcf72366ca4)
![image](https://github.com/redphx/apixoo/assets/7483947/e0e96901-0719-45f1-bfcc-bb8ff2ab1418)
![image](https://github.com/redphx/apixoo/assets/7483947/7280bba2-12ab-46ee-a969-696d1381dd91)
![image](https://github.com/redphx/apixoo/assets/7483947/720a1f95-91bd-457f-b595-de7bdeff88bb)

**Comment by redphx** [comment]
No it's unrelated.  
In Divoom's file, the 3rd and 4th bytes are speed, in this case it's `0x0041 = 65`. I'm not sure it's 65ms or something else.  
<img width="148" alt="image" src="https://github.com/redphx/apixoo/assets/96280/320f9aff-8e5f-4ad5-84e7-e5fc3576265e">

Could you please change [this line](https://github.com/redphx/apixoo/blob/main/apixoo/pixel_bean.py#L86) to:  
```
duration=self._speed,
```
and try again?

**Comment by baicker** [comment]
a ha, it's fixed, 
i change here before, but i changed to (self._speed/1000), havn't try the self._speed
it's ok now, thanks redphx !!!
